# Generated by Django 4.2.16 on 2024-09-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_resource_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='author',
            new_name='user',
        ),
    ]
