# Generated by Django 4.2.16 on 2024-09-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_author_resource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='attachment_extension',
            field=models.CharField(default='txt', max_length=20),
            preserve_default=False,
        ),
    ]
