# Generated by Django 4.2.16 on 2024-09-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_resource_attachment_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='attachment_extension',
            new_name='extension',
        ),
    ]
