# Generated by Django 4.2.16 on 2024-09-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_attachment_extension_resource_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='extension',
            new_name='attachment_extension',
        ),
        migrations.AddField(
            model_name='resource',
            name='attachment_name',
            field=models.CharField(default='ui', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='attachment_size',
            field=models.IntegerField(default='23'),
            preserve_default=False,
        ),
    ]
