# Generated by Django 4.2.16 on 2024-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_extension_resource_attachment_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.TextField(),
        ),
    ]
