# Generated by Django 4.2.16 on 2024-09-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
