# Generated by Django 4.2.16 on 2024-10-04 07:52

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_imageupload_image_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploads/', validators=[common.utils.validate_image_extension]),
        ),
    ]
