# Generated by Django 4.2.16 on 2024-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
    ]
