name: KidsDIY Backend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make .env
        run: |
          sudo echo "${{ secrets.ENV_FILE }}" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/diy:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into VPS instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            cd diy-backend
            sudo docker rm -f diy || true
            sudo docker system prune -af || true
            sudo docker pull  maximugisha/diy:latest || true
            docker run -d --env-file .env -p 8000:8000 -v media:/app/media --name diy maximugisha/diy:latest